# Generated by Django 3.1.3 on 2020-12-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201219_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('book', models.TextField(max_length=100)),
            ],
        ),
    ]
