# Generated by Django 3.1.3 on 2020-12-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_books_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_user',
            name='author',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books_user',
            name='book',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books_user',
            name='name',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
