# Generated by Django 3.1.3 on 2020-12-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_poems_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='musics_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('music', models.TextField(blank=True, max_length=100, null=True)),
                ('singer', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
