# Generated by Django 3.1.3 on 2020-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20201229_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poems_user',
            name='poem',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
